version: "3.7"

services:
  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    working_dir: /app
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - mynetwork
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
volumes:
  mysql_data:
networks:
  mynetwork:
